### ISSUE TITLE
关于时辰，早子时晚子时的讨论

### ISSUE THREAD

**Issue by consatan** [overtrue/chinese-calendar#13]
之前发 PR #12 的时候没考虑到早子时和晚子时对日柱的影响（怪百度百科里没说，哼都是百度的错）

今天在用别人的软件时发现
2018-03-31 23点 和 2018-03-31 00点 的农历是不一样的
23点的农历是 二月廿五子时
00点的农历是 二月廿四子时

google 了下，大部分的结论都是古时与子时为一天的开始，23点后就算新一天的开始，所以日柱应该加一天

所以当 `$hour` 参数为 23 时，是否有必要将日柱加一天？如果需要的话，我再提个 PR，顺便把 `$hour` 参数的说明在 README 更新下

参考: 
[早子與晚子都是子時](http://blog.xuite.net/mahdi743/twblog/136281222-%E6%97%A9%E5%AD%90%E8%88%87%E6%99%9A%E5%AD%90%E9%83%BD%E6%98%AF%E5%AD%90%E6%99%82)
[飄風點萃....有關.早子.與.晚子..乃至於..日柱的界定與關照..之ㄧ..](http://blog.xuite.net/jerry100630902/twblog/161762569-%E9%A3%84%E9%A2%A8%E9%BB%9E%E8%90%83....%E6%9C%89%E9%97%9C.%E6%97%A9%E5%AD%90.%E8%88%87.%E6%99%9A%E5%AD%90..%E4%B9%83%E8%87%B3%E6%96%BC..%E6%97%A5%E6%9F%B1%E7%9A%84%E7%95%8C%E5%AE%9A%E8%88%87%E9%97%9C%E7%85%A7..%E4%B9%8B%E3%84%A7..)
[子时，分早子时、晚子时？命理学上最画蛇添足的说法。](https://zhuanlan.zhihu.com/p/29797972)

**Comment by overtrue** [comment]
@consatan 如果 OK 的话就再 PR 吧，目前我这边工作比较忙，公司就我一个技术，哈哈，累成狗，如果逻辑 OK 请尽管 PR。
