### ISSUE TITLE
是否有必要改变默认时区？

### ISSUE THREAD

**Issue by hao-li** [overtrue/chinese-calendar#17]
https://github.com/overtrue/chinese-calendar/blob/ba1458ff33d4e53f4987fabb0d7dacc2505e3ad6/src/Calendar.php#L232

这个逻辑应该是 #5 时修改的，目前该 issue 涉及的 mktime 和 strtotime 被改成硬编码了，此逻辑是否可以一并删除？
另外因为看黄历的华人在不同时区均有分布，所以感觉一般还是使用 UTC 比较好

**Comment by overtrue** [comment]
已经删除了构造函数

**Comment by hao-li** [comment]
准备升级新版，请 release 一下

**Comment by overtrue** [comment]
@hao-li 已发布
