### ISSUE TITLE
composer require 出错

### ISSUE THREAD

**Issue by tlerbao** [overtrue/chinese-calendar#3]
Could not find package overtrue/chinese-calendar at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by tlerbao** [comment]
晕，安神你还没 releases 么？

**Comment by overtrue** [comment]
还没发版。。。

**Comment by tlerbao** [comment]
什么时候发呢，就等着用了哈

**Comment by overtrue** [comment]
我可以先发一版，生肖有 bug

**Comment by tlerbao** [comment]
生效用不上，现在需求就是一个生日字段，存的可能是农历也可能是阳历，要换算下具体的时间，然后做生日提醒。。。。蛋疼。

**Comment by overtrue** [comment]
https://github.com/overtrue/chinese-calendar/releases/tag/0.0.1

**Comment by tlerbao** [comment]
还有我这个菜鸡的想法，能否封装进更单纯的 时间换算，不要那些生肖啊，星座啊什么的
就 阳历 1985-07-19 转换农历 return 农历 1985-06-02 哈
如果无知，请开怀的笑。

**Comment by overtrue** [comment]
@tlerbao 我考虑一下，先用着

**Comment by tlerbao** [comment]
ok 能跟安神交流，很激动呢。
