### ISSUE TITLE
I found some php version get your dateDiff not correctly

### ISSUE THREAD

**Issue by nior2insect** [overtrue/chinese-calendar#48]
I found some php version get your dateDiff not same value.  I change from makeDate to date_create will work well.

    public function dateDiff($date1, $date2)
    {

        $date1 = date_create($date1);
        $date2 = date_create($date2);
        $diff = date_diff($date1,$date2);

        return $diff;

        /* Original
        if (!($date1 instanceof DateTime)) {
            $date1 = $this->makeDate($date1);
        }

        if (!($date2 instanceof DateTime)) {
            $date2 = $this->makeDate($date2);
        }

        return $date1->diff($date2);
        */
    }

**Comment by overtrue** [comment]
Plz make a PR.

**Comment by nior2insect** [comment]
Sorry sir, it's my fault.

I go find some reason and I found this *****The answer is timezone + normalize

https://stackoverflow.com/questions/40354442/why-does-php-datetime-diff-depend-on-time-zones

/************* Here I test to see date_diff by random timezone  ******************/

        $tzlist = DateTimeZone::listIdentifiers(DateTimeZone::ALL);
        shuffle($tzlist);
        for($i=0;$i<10;$i++){
            $this->printDiff($tzlist[$i], date_format($date, "Y-m-d"), '1900-01-31');
            echo "<br>";    
        }

/********** Here is result ********************/

America/Indiana/Petersburg
Year: 91 Month: 06 Day: 01 days: 33420

Pacific/Tongatapu
Year: 91 Month: 06 Day: 01 days: 33419

Africa/Kigali
Year: 91 Month: 06 Day: 02 days: 33420

Australia/Currie
Year: 91 Month: 06 Day: 02 days: 33420

Europe/Monaco
Year: 91 Month: 06 Day: 01 days: 33419

UTC
Year: 91 Month: 06 Day: 02 days: 33420

PRC
Year: 91 Month: 06 Day: 01 days: 33419

Asia/Shanghai
Year: 91 Month: 06 Day: 01 days: 33419

/********************************************************/

The answer for me is when $calendar->makeDate I have to set timezone that I use.

Your code is work perfectly.

Thanks you

**Comment by overtrue** [comment]
OK, Thanks.
