### ISSUE TITLE
lunar2solar 问题。。。

### ISSUE THREAD

**Issue by tlerbao** [overtrue/chinese-calendar#5]
#### lunar2solar 方法
```php
$calendar = new Calendar();
$result = $calendar->lunar2solar(2017, 04, 02);
```
返回：
```
array(3) {
  ["solar_year"] =&gt; string(4) "1951"
  ["solar_month"] =&gt; string(2) "03"
  ["solar_day"] =&gt; string(2) "01"
}
```

为什么是 1951年3月1日，农历 2017 四月初二 应该是今天 2017年4月27啊

**Comment by overtrue** [comment]
😆 无 fuck 说，肯定是 bug 了，但是这会儿我是真忙不过来搞它。请给我一些时间。

**Comment by tlerbao** [comment]
@overtrue 好，不急，那我就等了，找了N个农历阳历转换的类库，终于发现安神有这个轮子，**还是安神的代码长的好看。**

我还在 laravelChina 发了个贴，您忙完可以一并解答我这个菜鸡。
https://laravel-china.org/topics/4557/some-of-the-problems-of-soothing-chinese-calendar-ask-for-advice

**Comment by momosc** [comment]
$result = $calendar->lunar(2017, 4, 10); // 阴历  这个确实有问题

**Comment by tlerbao** [comment]
@momosc 有问题是的确的，但是安神 没有时间管这个轮子哈。

**Comment by tlerbao** [comment]
@overtrue 距离上次commit 已经一个月了，安神咱百忙之中家装抽空更新一下这个包呗，哪怕是修复一下bug。代码写的渣，实在不忍pr啊。

**Comment by overtrue** [comment]
@tlerbao 为啥我的是 
![image](https://cloud.githubusercontent.com/assets/1472352/25946285/0012fa24-367d-11e7-9c53-e6ac801e6a0b.png)

![image](https://cloud.githubusercontent.com/assets/1472352/25946290/04df511a-367d-11e7-94ad-8a41092e0cc5.png)

**Comment by overtrue** [comment]
@momosc `$calendar->lunar(2017, 4, 10)` 的结果为：

```json
{
    "lunar_year": 2017,
    "lunar_month": 4,
    "lunar_day": 10,
    "lunar_month_chinese": "四月",
    "lunar_day_chinese": "初十",
    "ganzhi_year": "丁酉",
    "ganzhi_month": "乙巳",
    "ganzhi_day": "壬辰",
    "animal": "鸡",
    "term": "立夏",
    "is_leap": false,
    "gregorian_year": "2017",
    "gregorian_month": "05",
    "gregorian_day": "05",
    "week_no": 5,
    "week_name": "星期五",
    "is_today": false,
    "constellation": "金牛"
}
```

我也去翻了其它万年历，都是一样的啊，你说的有问题是指？

**Comment by tlerbao** [comment]
@overtrue  直接用 lunar2solar 方法 返回信息不对啊。
```
$calendar = new Calendar();
$result = $calendar->lunar2solar(2017, 04, 02);
dump($result);
```

返回
```
array(3) {
  ["solar_year"] =&gt; string(4) "1951"
  ["solar_month"] =&gt; string(2) "02"
  ["solar_day"] =&gt; string(2) "21"
}
```

**Comment by overtrue** [comment]
对啊，我就是这样用的啊

**Comment by overtrue** [comment]
你的 PHP 版本是？

**Comment by tlerbao** [comment]
@overtrue 
Win10
php 5.6.27-nts + nginx

**Comment by overtrue** [comment]
靠，我的 PHP 7 是正常的，我换 5.6 试试

**Comment by overtrue** [comment]
@tlerbao 我的 5.6 也正常 😆

**Comment by tlerbao** [comment]
@overtrue 难道我活见鬼了？

**Comment by tlerbao** [comment]
@overtrue 主要上面也有个朋友说有问题哈

**Comment by overtrue** [comment]
建议你先更新看看，我觉得可能你装了旧版哈哈

**Comment by tlerbao** [comment]
@overtrue 我刚新 composer require overtrue/chinese-calendar -vvv 安装的

然后我切换到 php 7.0.12 还是上面一样的写法**报错了**
> Calendar.php line 646
> date() expects parameter 2 to be integer, float given

**Comment by tlerbao** [comment]
@overtrue 安神，有头绪么？是我的问题，还是怎样？

**Comment by overtrue** [comment]
我找其它人试一下

**Comment by jcc** [comment]
![175f0401-05cb-4db9-93a5-607422352e2d](https://cloud.githubusercontent.com/assets/12684082/25949085/edfeed82-3688-11e7-8411-37b795ec30a7.png)

![25320940-7cd9-4fe7-b1fb-da979a6e702f](https://cloud.githubusercontent.com/assets/12684082/25949088/ef45918c-3688-11e7-85d0-f7b36964b102.png)

@tlerbao 测试了一下是没问题的

**Comment by tlerbao** [comment]
@jcc 我去 那我活见鬼了？请问您是 win 还是mac php版本？

**Comment by tlerbao** [comment]
@overtrue 很怪 阳历就非常正常 阴历就都1951-x-x
```
$calendar->solar(2017, 5, 11); // 阳历就非常正常
$calendar->lunar(2017, 5, 11) // 阴历就1951年x月x日，醉醉的啊。
```

**Comment by tlerbao** [comment]
@overtrue 我调试了一下发现 645 行 
`$startTimestamp = mktime(0, 0, 0, 1, 30, 1900);`

这个$startTimestamp 是个bool(false) ,这似乎不正常。

**Comment by overtrue** [comment]
@tlerbao 把你的错误打开 `error_reporting(-1)`

**Comment by overtrue** [comment]
@tlerbao 更新版本

**Comment by tlerbao** [comment]
@overtrue 改成这样还是 $startTimestamp 还是返回false。
```
$startTimestamp = strtotime('1900-01-30 00:00:00');
dump($startTimestamp);
```
然后 
`($offset + $day) * 86400 + $startTimestamp`
返回的时间戳 拿 $calendar->lunar(2017, 05, 11) 来说 生成的是 3703104000，2087/5/7 8:0:0

我尽量详细了，在php5.6下不报错。

**Comment by tlerbao** [comment]
@overtrue php 5.6 开启 error_reporting(-1)
> Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in F:\WorkSpace\DolphinPHP\vendor\overtrue\chinese-calendar\src\Calendar.php on line 646

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in F:\WorkSpace\DolphinPHP\vendor\overtrue\chinese-calendar\src\Calendar.php on line 647

**Comment by overtrue** [comment]
所以需要设置时区嘛

**Comment by tlerbao** [comment]
@overtrue 设置时区不报错了，但依然是1951年。。。菜的抠脚啊我

**Comment by overtrue** [comment]
你是如何测试的？nginx 网页？

**Comment by tlerbao** [comment]
@overtrue 用你的test.php 开启error_reporting(-1);
```
echo json_encode($calendar->lunar(2017, 5, 11), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
```

直接chrome 访问 test.php ，，，出来的json数据还是1951年，但是不报错了，我用了你最新的代码

**Comment by overtrue** [comment]
你先保证你的 mktime 能正确返回吧。。。

**Comment by overtrue** [comment]
```sh
>>> mktime(0, 0, 0, 1, 30, 1900)
=> -2206483200

```

**Comment by tlerbao** [comment]
@overtrue 用你最新的代码为前提
1. 首先 strtotime('1900-01-30 00:00:00') 依然返回false。
2. mktime(0, 0, 0, 1, 30, 1900); 也是返回false。
3. 但是 mktime(0, 0, 0, 1, 30, 2017) 改成2017 可以返回1485705600 正确的时间戳。

怪不怪哈！

**Comment by tlerbao** [comment]
补充 strtotime('2017-01-30 00:00:00') 也可以正常返回正确的时间戳

为何 1900-01-30 00:00:00就false呢 怪了

**Comment by overtrue** [comment]
艹，加我 Q 吧

**Comment by overtrue** [comment]
44294631
